//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundleBoxingEnvio
    {
        public int IdEnvio { get; set; }
        public string CorteCompleto { get; set; }
        public string Corte { get; set; }
        public string Serial { get; set; }
        public Nullable<int> IdSaco { get; set; }
        public int Saco { get; set; }
        public int Bulto { get; set; }
        public int Yarda { get; set; }
        public int Polin { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdUsuarioInactiva { get; set; }
        public Nullable<System.DateTime> FechaInactivo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
