//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundleBoxing_Saco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BundleBoxing_Saco()
        {
            this.BundleBoxing = new HashSet<BundleBoxing>();
        }
    
        public int IdSaco { get; set; }
        public int Saco { get; set; }
        public string Corte { get; set; }
        public int Seccion { get; set; }
        public int IdUsuarioCrea { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Abierto { get; set; }
        public Nullable<int> IdUsuarioAbre { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BundleBoxing> BundleBoxing { get; set; }
    }
}
