//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassOunce
    {
        public int IdOunce { get; set; }
        public int Ounce { get; set; }
        public string Category { get; set; }
        public string FeedDog { get; set; }
        public string Caliber { get; set; }
    }
}
