//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorCorte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactorCorte()
        {
            this.FactorDetalleCorte = new HashSet<FactorDetalleCorte>();
        }
    
        public int IdFactorCorte { get; set; }
        public decimal Linearecta { get; set; }
        public decimal Curva { get; set; }
        public decimal Esquinas { get; set; }
        public decimal Piquetes { get; set; }
        public decimal HacerOrificio { get; set; }
        public decimal PonerTape { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactorDetalleCorte> FactorDetalleCorte { get; set; }
    }
}
