//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorTendido
    {
        public int IdFactor { get; set; }
        public int IdProcesoTendido { get; set; }
        public int NoFactor { get; set; }
        public decimal ValorFactor { get; set; }
    
        public virtual ProcesosTendido ProcesosTendido { get; set; }
    }
}
