//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorDetalleCorte
    {
        public int IdFactorDetalleCorte { get; set; }
        public int IdFactorCorte { get; set; }
        public string Item { get; set; }
        public string Componente { get; set; }
        public string Estilo { get; set; }
        public string LayLimits { get; set; }
        public int TotalPieces { get; set; }
        public decimal StraightPerimeter { get; set; }
        public decimal CurvedPerimeter { get; set; }
        public decimal TotalPerimeter { get; set; }
        public int TotalNotches { get; set; }
        public int TotalCorners { get; set; }
        public decimal Segundos { get; set; }
        public decimal Minutos_Pza { get; set; }
    
        public virtual FactorCorte FactorCorte { get; set; }
    }
}
