//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedDog
    {
        public int IdFeedDog { get; set; }
        public string Part { get; set; }
        public string MachineType { get; set; }
        public string ReferenceBrand { get; set; }
        public string ReferenceModel { get; set; }
        public string Position { get; set; }
        public string Category { get; set; }
        public string Code { get; set; }
    }
}
