//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineData
    {
        public int IdDataMachine { get; set; }
        public string Name { get; set; }
        public string Stitch { get; set; }
        public decimal Rpm { get; set; }
        public decimal Delay { get; set; }
        public decimal Personal { get; set; }
        public decimal Fatigue { get; set; }
        public string Nomenclature { get; set; }
        public string Machine { get; set; }
        public string Description { get; set; }
        public string Needle { get; set; }
    }
}
