//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int IdMaterial { get; set; }
        public string Material1 { get; set; }
        public int IdPresentacionSerial { get; set; }
        public bool Activo { get; set; }
    
        public virtual PresentacionSerial PresentacionSerial { get; set; }
    }
}
