//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodAnalysis
    {
        public int IdMethodAnalysis { get; set; }
        public string Codigo { get; set; }
        public string Operacion { get; set; }
        public int IdDataMachine { get; set; }
        public string DataMachine { get; set; }
        public decimal Puntadas { get; set; }
        public string ManejoPaquete { get; set; }
        public decimal Rate { get; set; }
        public decimal JornadaLaboral { get; set; }
        public int IdTela { get; set; }
        public decimal Onza { get; set; }
        public string MateriaPrima_1 { get; set; }
        public string MateriaPrima_2 { get; set; }
        public string MateriaPrima_3 { get; set; }
        public string MateriaPrima_4 { get; set; }
        public string MateriaPrima_5 { get; set; }
        public string MateriaPrima_6 { get; set; }
        public string MateriaPrima_7 { get; set; }
        public string ParteSeccion { get; set; }
        public string TipoConstruccion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual MachineData MachineData { get; set; }
        public virtual TipoTela TipoTela { get; set; }
    }
}
