//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodAnalysisDetalle
    {
        public int IdDetMethodAnalysis { get; set; }
        public string Codigo1 { get; set; }
        public string Codigo2 { get; set; }
        public string Codigo3 { get; set; }
        public string Codigo4 { get; set; }
        public string Descripcion { get; set; }
        public decimal Freq { get; set; }
        public decimal Tmus { get; set; }
        public decimal Sec { get; set; }
        public decimal Sam { get; set; }
    }
}
