//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocedesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanningSwing
    {
        public int IdPlaningSwing { get; set; }
        public string Week { get; set; }
        public int IdCliente { get; set; }
        public string Modulo { get; set; }
        public string Linea { get; set; }
        public Nullable<System.DateTime> Cut_date_all_component { get; set; }
        public string Ct { get; set; }
        public string Marker { get; set; }
        public decimal Largo { get; set; }
        public string NotasEspeciales { get; set; }
        public string Origen_segun_wip { get; set; }
        public string Cutting_plan { get; set; }
        public string Cut { get; set; }
        public string Style { get; set; }
        public Nullable<System.DateTime> Cut_date_body { get; set; }
        public Nullable<System.DateTime> foleo_date_body { get; set; }
        public Nullable<System.DateTime> In_plant { get; set; }
        public decimal Quant { get; set; }
        public string Status_comp { get; set; }
        public string Status_cuerpo { get; set; }
        public string Foleo { get; set; }
        public string Status_envio { get; set; }
        public string Fabric { get; set; }
        public string Pocketing { get; set; }
        public string Fuse1 { get; set; }
        public string Fuse2 { get; set; }
        public string Cordura { get; set; }
        public string Quilt { get; set; }
        public string Dracon { get; set; }
        public string Linning { get; set; }
        public string Binding1 { get; set; }
        public string Binding2 { get; set; }
        public string Sherpa { get; set; }
        public string Rib { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
